### ISSUE TITLE
生成报错

### ISSUE THREAD

**Issue by tanoak10** [starcwang/easy_javadoc#10]
java.lang.Throwable: cannot share data context between Swing events; initial event count = 30901; current event count = 31890
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:145)
	at com.intellij.ide.impl.DataManagerImpl$MyDataContext.getData(DataManagerImpl.java:341)
	at com.intellij.openapi.actionSystem.DataContext.getData(DataContext.java:55)
	at com.intellij.openapi.actionSystem.AnActionEvent.getData(AnActionEvent.java:184)
	at com.star.easydoc.action.GenerateAllJavadocAction.actionPerformed(GenerateAllJavadocAction.java:50)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:593)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$processAction$3(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:192)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:645)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:508)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:463)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:212)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:412)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:704)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:411)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by tanoak10** [comment]
版本，Mac 19.2
重现方式 cmd + shift +\

**Comment by starcwang** [comment]
已在1.4版本修复，等idea官方审核通过后更新即可~

**Comment by jzyhywxz** [comment]
@starcwang 您好，我最近也在学习intellij idea插件开发，并且我也遇到了这个问题，即：
```
java.lang.Throwable: cannot share data context between Swing events; initial event count = xxx; current event count = xxx
```
我发现抛出这个异常的相关代码是：
```java
public class MyActionListener extends MyListener implements AnActionListener {
    public void afterActionPerformed(AnAction anAction, DataContext dataContext, AnActionEvent anActionEvent) {
        Project project = anActionEvent.getData(CommonDataKeys.PROJECT);
        Editor editor = anActionEvent.getData(CommonDataKeys.EDITOR);
        ...
    }
}
```
请问您知道为什么会产生这个异常么？以及要如何做才能修复这个错误？万分感谢！

**Comment by starcwang** [comment]
看字面意思是不能在各个swing界面之间，共享事件上下文。
我改的方式是在父event中先拿出project，然后再传入子event中。你也可以这么试试。在创建MyActionListener的时候，把project等信息通过构造函数传进去。

**Comment by starcwang** [comment]
@jzyhywxz
看字面意思是不能在各个swing界面之间，共享事件上下文。
我改的方式是在父event中先拿出project，然后再传入子event中。你也可以这么试试。在创建MyActionListener的时候，把project等信息通过构造函数传进去。

**Comment by jzyhywxz** [comment]
@starcwang 
谢谢您！按照您的说法是可行的，不过除此之外我又想到了其他方法。实际上我想在action performed的时候拿到当前的project和editor，对于当前的project可以用以下代码得到：
```java
public static Project getActiveProject() {
        Project[] projects = ProjectManager.getInstance().getOpenProjects();
        if (projects == null || projects.length <= 0) {
            return null;
        }

        Project activeProject = null;
        for (Project project : projects) {
            Window window = WindowManager.getInstance().suggestParentWindow(project);
            if (window != null && window.isActive()) {
                activeProject = project;
            }
        }
        return activeProject;
    }
```
但我还不知道如何得到当前的editor。

事实上，我并没有在插件中创建任何Project级别的构件（Project level components），而是只创建了一个Application级别的构件（Application level components）。因此，按照您的解决方案，另一种方法就是实现`ProjectManagerListener`接口，并在该接口的`projectOpened`方法中注册`AnActionListener`实例，在`projectClosed`方法中注销相应的`AnActionListener`实例。由于在`projectOpened`方法中可以得到一个`Project`实例，因此可以在创建`AnActionListener`对象时通过构造函数把这个`Project`实例传进去，也就是您说的方法。

十分感谢您的帮助！:smile:
