### ISSUE TITLE
默认的【有道翻译】已被官方禁用，请申请个人账号使用，各个服务商都可以免费使用

### ISSUE THREAD

**Issue by starcwang** [starcwang/easy_javadoc#115]

**Comment by fhqmwy** [comment]
我申请并设置了 百度翻译 但是好像还是没有用 会报一个错误，空指针

**Comment by fhqmwy** [comment]
> 我申请并设置了 百度翻译 但是好像还是没有用 会报一个错误，空指针

 java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "com.star.easydoc.service.translator.impl.BaiduTranslator$BaiduResponse.getTransResult()" is null
at com.star.easydoc.service.translator.impl.BaiduTranslator.get(BaiduTranslator.java:61)

**Comment by MiniFullC** [comment]
插件中必须设置各翻译引擎的key。
但微软翻译、谷歌翻译有公共接口，不需要key就可以调用。
希望作者可以改一下~

**Comment by hufengwei0315** [comment]
java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because the return value of "com.star.easydoc.service.translator.impl.YoudaoAiTranslator$YoudaoAiResponse.getTranslation()" is null
	at com.star.easydoc.service.translator.impl.YoudaoAiTranslator.translate(YoudaoAiTranslator.java:56)
	at com.star.easydoc.service.translator.impl.YoudaoAiTranslator.translateEn2Ch(YoudaoAiTranslator.java:28)
	at com.star.easydoc.service.translator.impl.AbstractTranslator.en2Ch(AbstractTranslator.java:30)
	at com.star.easydoc.service.translator.TranslatorService.getFromOthers(TranslatorService.java:218)
	at com.star.easydoc.service.translator.TranslatorService.translate(TranslatorService.java:101)
	at com.star.easydoc.javadoc.service.variable.impl.DocVariableGenerator.generate(DocVariableGenerator.java:32)
	at com.star.easydoc.javadoc.service.variable.JavadocVariableGeneratorService.generate(JavadocVariableGeneratorService.java:80)
	at com.star.easydoc.javadoc.service.generator.impl.MethodDocGenerator.customGenerate(MethodDocGenerator.java:307)
	at com.star.easydoc.javadoc.service.generator.impl.MethodDocGenerator.generate(MethodDocGenerator.java:57)
	at com.star.easydoc.javadoc.service.JavaDocGeneratorServiceImpl.generate(JavaDocGeneratorServiceImpl.java:46)
	at com.star.easydoc.action.GenerateJavadocAction.javadocProcess(GenerateJavadocAction.java:134)
	at com.star.easydoc.action.GenerateJavadocAction.actionPerformed(GenerateJavadocAction.java:106)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:599)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)


使用有道云翻译也会有类似问题

**Comment by starcwang** [comment]
@MiniFullC 有例子吗？发我我瞅瞅

**Comment by starcwang** [comment]
@hufengwei0315 你请求的是https://openapi.youdao.com/api地址不？方便的话发我下样例，可以去掉key

**Comment by starcwang** [comment]
@fhqmwy 百度请求的是 http://api.fanyi.baidu.com/api/trans/vip/translate?from=auto&to=auto&appid=%s&salt=%s&sign=%s&q=%s 吗？方便的话发我下样例，可以去掉key

**Comment by MiniFullC** [comment]
> @MiniFullC Got an example? Send it to me and I'll take a look.

* [微软翻译 ](https://github.com/YiiGuxing/TranslationPlugin/blob/d12e7449489d5400e9b2587673199e384aca6335/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/microsoft/MicrosoftTranslatorService.kt#L136)

* [谷歌翻译 ](https://github.com/YiiGuxing/TranslationPlugin/blob/d12e7449489d5400e9b2587673199e384aca6335/src/main/kotlin/cn/yiiguxing/plugin/translate/trans/google/GoogleTranslator.kt#L80)

**Comment by myjjack** [comment]
我申请了，有道翻译api，但是设置里的有道翻译不支持，应用ID和应用秘钥的输入。

**Comment by starcwang** [comment]
@myjjack 选有道智云翻译

**Comment by kulalasmile** [comment]
请求阿里云翻译接口异常：请检查本地网络是否可连接外网，也有可能被阿里云限流
java.lang.NullPointerException: Cannot invoke "com.star.easydoc.service.translator.impl.AliyunTranslator$AliyunResponseDataVO.getTranslated()" because the return value of "com.star.easydoc.service.translator.impl.AliyunTranslator$AliyunResponseVO.getData()" is null
	at com.star.easydoc.service.translator.impl.AliyunTranslator.translate(AliyunTranslator.java:66)
	at com.star.easydoc.service.translator.impl.AliyunTranslator.translateEn2Ch(AliyunTranslator.java:47)
	at com.star.easydoc.service.translator.impl.AbstractTranslator.en2Ch(AbstractTranslator.java:30)
	at com.star.easydoc.service.translator.TranslatorService.getFromOthers(TranslatorService.java:174)
	at com.star.easydoc.service.translator.TranslatorService.translate(TranslatorService.java:84)
	at com.star.easydoc.javadoc.service.variable.impl.DocVariableGenerator.generate(DocVariableGenerator.java:34)
	at com.star.easydoc.javadoc.service.variable.JavadocVariableGeneratorService.generate(JavadocVariableGeneratorService.java:80)
	at com.star.easydoc.javadoc.service.generator.impl.MethodDocGenerator.customGenerate(MethodDocGenerator.java:282)
	at com.star.easydoc.javadoc.service.generator.impl.MethodDocGenerator.generate(MethodDocGenerator.java:54)
	at com.star.easydoc.javadoc.service.JavaDocGeneratorServiceImpl.generate(JavaDocGeneratorServiceImpl.java:46)
	at com.star.easydoc.action.GenerateJavadocAction.javadocProcess(GenerateJavadocAction.java:134)
	at com.star.easydoc.action.GenerateJavadocAction.actionPerformed(GenerateJavadocAction.java:106)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:599)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by zd925** [comment]
有哪个服务商成功了嘛？推荐一波

**Comment by starcwang** [comment]
@zd925 最新版所有服务商都支持呀

**Comment by skyais** [comment]
插件在新版idea中使用报错。
java.lang.NullPointerException: Cannot invoke "com.star.easydoc.config.EasyDocConfig.getWordMapWithProject()" because "this.config" is null
idea版本： 2023.2.1 (Ultimate Edition)
