### ISSUE TITLE
  请求阿里云翻译接口异常 ，本地网络连接外网，刚刚创建阿里云账户

### ISSUE THREAD

**Issue by zd925** [starcwang/easy_javadoc#116]
请求阿里云翻译接口异常：请检查本地网络是否可连接外网，也有可能被阿里云限流
  
  java.lang.NullPointerException: Cannot invoke "com.star.easydoc.service.translator.impl.AliyunTranslator$AliyunResponseDataVO.getTranslated()" because the return value of "com.star.easydoc.service.translator.impl.AliyunTranslator$AliyunResponseVO.getData()" is null
at com.star.easydoc.service.translator.impl.AliyunTranslator.translate(AliyunTranslator.java:66)
at com.star.easydoc.service.translator.impl.AliyunTranslator.translateEn2Ch(AliyunTranslator.java:47)
at com.star.easydoc.service.translator.impl.AbstractTranslator.en2Ch(AbstractTranslator.java:30)
at com.star.easydoc.service.translator.TranslatorService.getFromOthers(TranslatorService.java:174)
at com.star.easydoc.service.translator.TranslatorService.translate(TranslatorService.java:94)
at com.star.easydoc.javadoc.service.generator.impl.FieldDocGenerator.genNormalDoc(FieldDocGenerator.java:88)
at com.star.easydoc.javadoc.service.generator.impl.FieldDocGenerator.defaultGenerate(FieldDocGenerator.java:60)
at com.star.easydoc.javadoc.service.generator.impl.FieldDocGenerator.generate(FieldDocGenerator.java:43)
at com.star.easydoc.javadoc.service.JavaDocGeneratorServiceImpl.generate(JavaDocGeneratorServiceImpl.java:46)
at com.star.easydoc.action.GenerateJavadocAction.javadocProcess(GenerateJavadocAction.java:134)
at com.star.easydoc.action.GenerateJavadocAction.actionPerformed(GenerateJavadocAction.java:106)
at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
at com.intellij.openapi.actionSystem.ex.ActionUtil.invokeAction(ActionUtil.java:538)
at com.intellij.ui.popup.ActionPopupStep.performAction(ActionPopupStep.java:266)
at com.intellij.ui.popup.ActionPopupStep.lambda$onChosen$3(ActionPopupStep.java:243)
at com.intellij.ui.popup.AbstractPopup.lambda$dispose$18(AbstractPopup.java:1625)
at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$3(FocusManagerImpl.java:173)
at com.intellij.util.ui.EdtInvocationManager.invokeLaterIfNeeded(EdtInvocationManager.java:33)
at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.kt:210)
at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.kt:176)
at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:169)
at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:163)
at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1623)
at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:165)
at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:394)
at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.dispose(PopupFactoryImpl.java:293)
at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:129)
at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:161)
at com.intellij.openapi.util.Disposer.dispose(Disposer.java:262)
at com.intellij.openapi.util.Disposer.dispose(Disposer.java:250)
at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:273)
at com.intellij.ui.popup.list.ListPopupImpl.disposePopup(ListPopupImpl.java:496)
at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:523)
at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:483)
at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:429)
at com.intellij.ui.popup.PopupFactoryImpl$ActionGroupPopup.handleSelect(PopupFactoryImpl.java:305)
at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:281)
at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:400)
at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:372)
at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:115)
at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:157)
at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:111)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:565)
at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by aopmin** [comment]
同问

**Comment by starcwang** [comment]
@aopmin @zd925 v3.5.2 已修复

**Comment by glowxq** [comment]
这个问题我更新到最新版后依然存在
