### ISSUE TITLE
最近使用的时候，请求有道翻译接口异常，无法自动生成注释

### ISSUE THREAD

**Issue by caishaodong** [starcwang/easy_javadoc#128]
IDEA中报了一个这样的错误提示，麻烦看下是什么原因？

请求有道翻译接口异常：请检查本地网络是否可连接外网，也有可能已经被有道限流

java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at com.star.easydoc.service.translator.impl.YoudaoTranslator.translateEn2Ch(YoudaoTranslator.java:28)
	at com.star.easydoc.service.translator.impl.AbstractTranslator.en2Ch(AbstractTranslator.java:26)
	at com.star.easydoc.service.TranslatorService.getFromOthers(TranslatorService.java:153)
	at com.star.easydoc.service.TranslatorService.translate(TranslatorService.java:67)
	at com.star.easydoc.service.variable.impl.DocVariableGenerator.generate(DocVariableGenerator.java:35)
	at com.star.easydoc.service.VariableGeneratorService.generate(VariableGeneratorService.java:106)
	at com.star.easydoc.service.generator.impl.MethodDocGenerator.customGenerate(MethodDocGenerator.java:278)
	at com.star.easydoc.service.generator.impl.MethodDocGenerator.generate(MethodDocGenerator.java:50)
	at com.star.easydoc.service.DocGeneratorService.generate(DocGeneratorService.java:42)
	at com.star.easydoc.action.GenerateJavadocAction.actionPerformed(GenerateJavadocAction.java:60)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:65)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:563)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$8(IdeKeyEventDispatcher.java:677)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:670)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:603)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:574)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:457)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:450)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:218)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:798)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by starcwang** [comment]
升级一下最新版插件。免费有道翻译被官方禁了，已经用不了了
