### ISSUE TITLE
使用整个文件增加翻译的时候报错，增加不上

### ISSUE THREAD

**Issue by yangle94** [starcwang/easy_javadoc#166]
2024-07-16 10:58:52,644 [ 144697] SEVERE - #c.i.i.p.PluginManager - class de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder cannot be cast to class com.intellij.psi.impl.source.PsiMethodImpl (de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @454dbc5f; com.intellij.psi.impl.source.PsiMethodImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3d4c975a)
        java.lang.ClassCastException: class de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder cannot be cast to class com.intellij.psi.impl.source.PsiMethodImpl (de.plushnikov.intellij.plugin.psi.LombokLightMethodBuilder is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @454dbc5f; com.intellij.psi.impl.source.PsiMethodImpl is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @3d4c975a)
        at com.star.easydoc.javadoc.service.variable.impl.ParamsVariableGenerator.generate(ParamsVariableGenerator.java:43)
        at com.star.easydoc.javadoc.service.variable.JavadocVariableGeneratorService.generate(JavadocVariableGeneratorService.java:80)
        at com.star.easydoc.javadoc.service.generator.impl.MethodDocGenerator.generate(MethodDocGenerator.java:67)
        at com.star.easydoc.javadoc.service.JavaDocGeneratorServiceImpl.generate(JavaDocGeneratorServiceImpl.java:47)
        at com.star.easydoc.action.GenerateAllJavadocAction.saveJavadoc(GenerateAllJavadocAction.java:208)
        at com.star.easydoc.action.GenerateAllJavadocAction.genMethodJavadoc(GenerateAllJavadocAction.java:181)
        at com.star.easydoc.action.GenerateAllJavadocAction.lambda$genClassJavadoc$2(GenerateAllJavadocAction.java:162)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
        at com.star.easydoc.action.GenerateAllJavadocAction.genClassJavadoc(GenerateAllJavadocAction.java:162)
        at com.star.easydoc.action.GenerateAllJavadocAction.javadocProcess(GenerateAllJavadocAction.java:134)
        at com.star.easydoc.action.GenerateAllJavadocAction.actionPerformed(GenerateAllJavadocAction.java:70)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:333)
        at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:585)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:707)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:707)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:356)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:704)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:648)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:596)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:480)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:469)
        at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
        at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.kt:599)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:569)
        at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:995)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
        at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:995)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:829)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
        2024-07-16 10:58:52,646 [ 144699] SEVERE - #c.i.i.p.PluginManager - IntelliJ IDEA 2023.1.7  Build #IU-231.9423.9
        2024-07-16 10:58:52,647 [ 144700] SEVERE - #c.i.i.p.PluginManager - JDK: 17.0.10; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
        2024-07-16 10:58:52,647 [ 144700] SEVERE - #c.i.i.p.PluginManager - OS: Windows 11
        2024-07-16 10:58:52,648 [ 144701] SEVERE - #c.i.i.p.PluginManager - Plugin to blame: Easy Javadoc version: 4.1.0

**Comment by starcwang** [comment]
此问题已在 v4.5.2 版本中修复。修复内容：将 ParamsVariableGenerator 中的类型转换从 ((PsiMethodImpl)element) 改为 ((PsiMethod)element)，使用接口而非具体实现类，以兼容 Lombok 插件生成的代码。
