### ISSUE TITLE
[kdoc] failed to initialize

### ISSUE THREAD

**Issue by kuolemax** [starcwang/easy_javadoc#71]
同时安装了easy-kdoc 和 easy-javadoc时会报错下面这个

```
OS: MacOS 13.1 Beta版(22C5050e) m1pro
IDEA: IntelliJ IDEA 2022.2.4 (Ultimate Edition)
```

Stacktrace.txt
```
Plugin 'com.star.easydoc.easy-kdoc' failed to initialize and will be disabled. Please restart IntelliJ IDEA.

com.intellij.diagnostic.PluginException: Key com.star.easydoc.service.WriterService duplicated; existingAdapter: ServiceAdapter(descriptor=ServiceDescriptor(interface='null', serviceImplementation='com.star.easydoc.service.WriterService', testServiceImplementation='null', headlessImplementation='null', overrides=false, configurationSchemaKey='null', preload=FALSE, client=null), pluginDescriptor=PluginDescriptor(name=Easy Javadoc, id=com.star.easydoc.easy-javadoc, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2022.2/plugins/easy_javadoc-1.29.jar, version=1.29, package=null, isBundled=false)); descriptor: com.star.easydoc.service.WriterService; app: Application  (containerState PRE_INIT) ; current plugin: com.star.easydoc.easy-kdoc
    at com.intellij.serviceContainer.ComponentManagerImpl.registerServices(ComponentManagerImpl.kt:501)
    at com.intellij.serviceContainer.ComponentManagerImpl.registerComponents(ComponentManagerImpl.kt:250)
    at com.intellij.openapi.client.ClientAwareComponentManager.registerComponents(ClientAwareComponentManager.kt:63)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt:148)
    at com.intellij.idea.ApplicationLoader$initApplication$block$3.apply(ApplicationLoader.kt)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1163)
    at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
    at com.intellij.idea.ApplicationLoader$initApplication$block$2.execute(ApplicationLoader.kt:142)
    at java.base/java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:572)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1147)
    at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
    at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
    at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1163)
    at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

只安装easy-kdoc时启动不会报错, 但是使用快捷键生成doc时会报错

```
java.lang.NullPointerException: Cannot invoke "com.star.easydoc.common.config.EasyDocConfig.getWordMap()" because "this.config" is null
	at com.star.easydoc.service.translator.TranslatorService.getFromCustom(TranslatorService.java:164)
	at com.star.easydoc.service.translator.TranslatorService.translate(TranslatorService.java:64)
	at com.star.easydoc.kdoc.service.variable.impl.DocVariableGenerator.generate(DocVariableGenerator.kt:22)
	at com.star.easydoc.kdoc.service.variable.VariableGeneratorService.generate(VariableGeneratorService.kt:67)
	at com.star.easydoc.kdoc.service.generator.impl.KtClassDocGenerator.defaultGenerate(KtClassDocGenerator.kt:40)
	at com.star.easydoc.kdoc.service.generator.impl.KtClassDocGenerator.generate(KtClassDocGenerator.kt:27)
	at com.star.easydoc.kdoc.service.DocGeneratorService.generate(DocGeneratorService.kt:35)
	at com.star.easydoc.kdoc.action.GenerateKdocAction.actionPerformed(GenerateKdocAction.kt:52)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:714)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:658)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:606)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:489)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:229)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

最后, 非常感谢您抽出时间做kdoc版!

**Comment by starcwang** [comment]
第一个应该是快捷键冲突了。我改下默认快捷键，想想用啥好。
第二个重启下idea试试。

**Comment by kuolemax** [comment]
> 第一个应该是快捷键冲突了。我改下默认快捷键，想想用啥好。 第二个重启下idea试试。

1. 安装完插件后无法apply或者ok, 点一下就会重新scan index,但是不会应用上, 还是那个错误信息, 然后我就将easy-javadoc的快捷键删除了, 但是依旧不行. 重启idea后会导致启动报错, 然后idea会直接启用所有插件, 关闭easy-kdoc.
2. 我将easy-javadoc关闭后只启用easy-kdoc可以正常应用, 但是在使用cmd+\生成kdoc时出现了新的error.
```kotlin
// 这个fun生成kdoc时error
fun replicatedData(origin: Any, target: Any)
// 包括上面那个fun, 第一次error后再次使用快捷键没有反应
fun earlyWarningBuild(publishDataLiveDetail: PublishDataLiveDetail,
                          violationRecord: ViolationRecord,
                          level:String,
                          vehicleInfo: Vehicle,
                          company: Company,
                          alarmArea:String,
                          alarmDesc:String)
// 这些是正常的
inline fun <reified T> T.logs(vararg annotation:String):T
fun process(
        publishDataLiveDetail: PublishDataLiveDetail,
        terminal: Terminal,
        gpsLive: GpsLive,
        vehicle: Vehicle,
        company: Company
    ): Int
// object暂时没有效果
object AlarmCategoryDao : Table<AlarmCategory>("alarm_category")

```

Stacktrace
```
kotlin.KotlinNullPointerException
	at com.star.easydoc.kdoc.service.generator.impl.KtNamedFunctionDocGenerator.getMethodInnerVariable(KtNamedFunctionDocGenerator.kt:77)
	at com.star.easydoc.kdoc.service.generator.impl.KtNamedFunctionDocGenerator.defaultGenerate(KtNamedFunctionDocGenerator.kt:50)
	at com.star.easydoc.kdoc.service.generator.impl.KtNamedFunctionDocGenerator.generate(KtNamedFunctionDocGenerator.kt:31)
	at com.star.easydoc.kdoc.service.DocGeneratorService.generate(DocGeneratorService.kt:35)
	at com.star.easydoc.kdoc.action.GenerateKdocAction.actionPerformed(GenerateKdocAction.kt:52)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:315)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:717)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:337)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:714)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:658)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:606)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:489)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:229)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:824)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:450)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:791)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:449)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:624)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:447)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:881)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:493)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by starcwang** [comment]
感谢反馈！我对kotlin的语法还不是很了解，上面的写法我适配一下

**Comment by starcwang** [comment]
已发布3.0.0版本 `Easy Javadoc` ，集成了javadoc和kdoc
