### ISSUE TITLE
阿里云翻译无法正常使用

### ISSUE THREAD

**Issue by suxilee** [starcwang/easy_javadoc#79]
操作系统：win10
IDEA版本：IntelliJ IDEA 2022.3.1 (Ultimate Edition)
插件版本：3.1.0
报错描述：同类型翻译插件Transaction填入阿里云密钥能正常使用，本插件填入同样密钥时
报错信息：
请求阿里云翻译接口异常：请检查本地网络是否可连接外网，也有可能被阿里云限流

java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at com.star.easydoc.service.translator.impl.AliyunTranslator.translate(AliyunTranslator.java:66)
	at com.star.easydoc.service.translator.impl.AliyunTranslator.translateEn2Ch(AliyunTranslator.java:47)
	at com.star.easydoc.service.translator.impl.AbstractTranslator.en2Ch(AbstractTranslator.java:30)
	at com.star.easydoc.service.translator.TranslatorService.getFromOthers(TranslatorService.java:173)
	at com.star.easydoc.service.translator.TranslatorService.translate(TranslatorService.java:86)
	at com.star.easydoc.javadoc.service.generator.impl.FieldDocGenerator.genNormalDoc(FieldDocGenerator.java:95)
	at com.star.easydoc.javadoc.service.generator.impl.FieldDocGenerator.defaultGenerate(FieldDocGenerator.java:59)
	at com.star.easydoc.javadoc.service.generator.impl.FieldDocGenerator.generate(FieldDocGenerator.java:42)
	at com.star.easydoc.javadoc.service.JavaDocGeneratorServiceImpl.generate(JavaDocGeneratorServiceImpl.java:46)
	at com.star.easydoc.action.GenerateJavadocAction.javadocProcess(GenerateJavadocAction.java:132)
	at com.star.easydoc.action.GenerateJavadocAction.actionPerformed(GenerateJavadocAction.java:104)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:323)
	at com.intellij.openapi.keymap.impl.ActionProcessor.performAction(ActionProcessor.java:47)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$1.performAction(IdeKeyEventDispatcher.java:584)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$9(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.lambda$doPerformActionInner$10(IdeKeyEventDispatcher.java:706)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:346)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.doPerformActionInner(IdeKeyEventDispatcher.java:703)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:647)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processActionOrWaitSecondStroke(IdeKeyEventDispatcher.java:478)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.inInitState(IdeKeyEventDispatcher.java:467)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:225)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:815)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:750)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:772)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by suxilee** [comment]
DNS问题，Transaction有缓存所以能正常使用
